FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    alibi-detect==0.11.4 \
    "scipy<1.12" \
    dill==0.3.6 \
    pandas \
    scikit-learn \
    numpy

COPY src/drift /app/src/drift
COPY data /app/data

# Default command to train and save the detector
CMD ["python", "src/drift/train_detector.py"]
