train:
  # Experiment configuration
  experiment_name: "wine_quality_optimization"
  seed: 42
  
  # Search space for hyperparameter tuning
  # Set enabled_algorithms to choose which models to sweep
  enabled_algorithms: 
    - elastic_net
    - random_forest

  search_space:
    elastic_net:
      alpha: [0.1]
      l1_ratio: [0.1]
    random_forest:
      n_estimators: [50]
      max_depth: [5]

